---
title: "HPclicks average sound pressure level"
author: "Lina Fliess"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r librarys, echo=FALSE}
library(readxl)
library(ggplot2)
```

```{r data DE, echo=FALSE}
Ref_DE_Aschau <- read_excel("AS_78 2023 02 28 FPOD_6889_train_details_filtered.xlsx")
Ref_DE_BoEck <- read_excel("BoEck 2023 02 07 FPOD_6877_train_details.xlsx")
Ref_DE_Langholz <- read_excel("LA_77 2023 02 28 FPOD_6888_train_details_filtered.xlsx")
#bind all dataframes from german ref stations
Ref_DE <- rbind(Ref_DE_Aschau, Ref_DE_BoEck, Ref_DE_Langholz)
```

```{r data DK, echo=FALSE}     
Ref_DK_6621 <- read_excel("2023 02 21 FPOD_6621 file0_train_details.xlsx")
Ref_DK_6623 <- read_excel("2023 02 21  2023 02 21 FPOD_6623 file0 train details.xlsx")
Ref_DK_6625 <- read_excel("20230221 2023 02 21 FPOD_6625 file0 train details.xlsx")
#bind all dataframes from danish ref stations
Ref_DK <- rbind(Ref_DK_6621, Ref_DK_6623, Ref_DK_6625)
```

```{r groups, echo=FALSE} 
Ref_DE_Aschau$group <- 'Aschau'
Ref_DE_BoEck$group <- 'BoEck'
Ref_DE_Langholz$group <- 'Langholz'
Ref_DE <- rbind(Ref_DE_Aschau, Ref_DE_BoEck, Ref_DE_Langholz)
Ref_DK_6621$group <- '6621'
Ref_DK_6623$group <- '6623'
Ref_DK_6625$group <- '6625'
Ref_DK <- rbind(Ref_DK_6621, Ref_DK_6623, Ref_DK_6625)
Ref_both <- rbind(Ref_DE,Ref_DK)
```

## <span style="color:blue">Comparison of average sound Pressure Level</span>###

# Germany

### Exploratory Analysis

```{r summarys DE}
summary(Ref_DE_Aschau$avSPL)
summary(Ref_DE_BoEck$avSPL)
summary(Ref_DE_Langholz$avSPL)
```

###Visualization/Plots:

```{r histogram DE, echo=FALSE}
ggplot(Ref_DE, aes(x = avSPL, fill = group)) +
  geom_histogram(bins = 50, alpha = 0.5, position = "identity") +
  labs(title = "Average Sound Pressure Level Distribution", x = "Average Sound Pressure Level", y = "Count") +
  scale_fill_manual(name = "Dataset", 
                    values = c('Aschau' = 'blue',
                               'BoEck' = 'green',
                               'Langholz' = 'darkcyan')) +
  theme(legend.position = "right")
```


```{r density plot DE, echo=FALSE}
ggplot(Ref_DE, aes(x = avSPL, fill = group)) +
  geom_density(bins = 50, alpha = 0.5, position = "identity") +
  labs(title = "Average Sound Pressure Level Distribution", x = "Average Sound Pressure Level", y = "Count") +
  scale_fill_manual(name = "Dataset", 
                    values = c('Aschau' = 'blue',
                               'BoEck' = 'green',
                               'Langholz' = 'darkcyan')) +
  theme(legend.position = "right")
```

```{r boxplot DE, echo=FALSE}
ggplot(Ref_DE, aes(x = group, y = avSPL, fill = group)) +
  geom_boxplot() +
  labs(title = "Boxplot of Average Sound Pressure Level", x = "Group", y = "Average Sound Pressure Level") +
  theme_minimal()
```

```{r scatter plot DE, echo=FALSE}
ggplot(Ref_DE, aes(x = group, y = avSPL, color = group)) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  labs(title = "Scatter Plot of Average Sound Pressure Level", x = "Group", y = "Average Sound Pressure Level") +
  theme_minimal()
```

### Statistical Test (Kruskal-Wallis)

```{r test DE, echo=FALSE}
kruskal.test(data = Ref_DE, avSPL ~ group)
```

# Denmark

### Exploratory Analysis

```{r summarys DK}
summary(Ref_DK_6621$avSPL)
summary(Ref_DK_6623$avSPL)
summary(Ref_DK_6625$avSPL)
```

###Visualization/Plots:

```{r histogram DK, echo=FALSE}
ggplot(Ref_DK, aes(x = avSPL, fill = group)) +
  geom_histogram(bins = 50, alpha = 0.5, position = "identity") +
  labs(title = "Average Sound Pressure Level Distribution", x = "Average Sound Pressure Level", y = "Count") +
  scale_fill_manual(name = "Dataset", 
                    values = c('6621' = 'gold', 
                               '6623' = 'orange', 
                               '6625' = 'red')) +
  theme(legend.position = "right")
```

```{r density plot DK, echo=FALSE}
ggplot(Ref_DK, aes(x = avSPL, fill = group)) +
  geom_density(bins = 50, alpha = 0.5, position = "identity") +
  labs(title = "Average Sound Pressure Level Distribution", x = "Average Sound Pressure Level", y = "Count") +
  scale_fill_manual(name = "Dataset", 
                    values = c('6621' = 'gold', 
                               '6623' = 'orange', 
                               '6625' = 'red')) +
  theme(legend.position = "right")
```

```{r boxplot DK, echo=FALSE}
ggplot(Ref_DK, aes(x = group, y = avSPL, fill = group)) +
  geom_boxplot() +
  labs(title = "Boxplot of Average Sound Pressure Level", x = "Group", y = "Average Sound Pressure Level") +
  theme_minimal()
```

```{r scatter plot DK, echo=FALSE}
ggplot(Ref_DK, aes(x = group, y = avSPL, color = group)) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  labs(title = "Scatter Plot of Average Sound Pressure Level", x = "Group", y = "Average Sound Pressure Level") +
  theme_minimal()
```

### Statistical Test (Kruskal-Wallis)

```{r test DK, echo=FALSE}
kruskal.test(data = Ref_DK, avSPL ~ group)
```

# Germany & Denmark

### Exploratory Analysis

```{r summarys DE/DK}
summary(Ref_DE_Aschau$avSPL)
summary(Ref_DE_BoEck$avSPL)
summary(Ref_DE_Langholz$avSPL)
summary(Ref_DK_6621$avSPL)
summary(Ref_DK_6623$avSPL)
summary(Ref_DK_6625$avSPL)
```

###Visualization/Plots:

```{r histogram DE/DK, echo=FALSE}
ggplot(Ref_both, aes(x = avSPL, fill = group)) +
  geom_histogram(bins = 50, alpha = 0.5, position = "identity") +
  labs(title = "Average Sound Pressure Level Distribution", x = "Average Sound Pressure Level", y = "Count") +
  scale_fill_manual(name = "Dataset", 
                    values = c('Aschau' = 'blue',
                               'BoEck' = 'green',
                               'Langholz' = 'darkcyan',
                               '6621' = 'gold', 
                               '6623' = 'orange', 
                               '6625' = 'red')) +
  theme(legend.position = "right")
```

```{r density plot2 DE/DK, echo=FALSE}
ggplot(Ref_both, aes(x = avSPL, fill = group)) +
  geom_density(bins = 50, alpha = 0.5, position = "identity") +
  labs(title = "Average Sound Pressure Level Distribution", x = "Average Sound Pressure Level", y = "Count") +
  theme_minimal()
```

```{r boxplot DE/DK, echo=FALSE}
ggplot(Ref_both, aes(x = group, y = avSPL, fill = group)) +
  geom_boxplot() +
  labs(title = "Boxplot of Average Sound Pressure Level", x = "Group", y = "Average Sound Pressure Level") +
  theme_minimal()
```

```{r scatter plot DE/DK, echo=FALSE}
ggplot(Ref_both, aes(x = group, y = avSPL, color = group)) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  labs(title = "Scatter Plot of Average Sound Pressure Level", x = "Group", y = "Average Sound Pressure Level") +
  theme_minimal()
```

### Statistical Test (Kruskal-Wallis)

```{r test DE/DK, echo=FALSE}
kruskal_result <- kruskal.test(data = Ref_both, avSPL ~ group)
```

```{r effect DE/DK, echo=FALSE}
H <- kruskal_result$statistic
# Extract the p-value (if needed for reporting)
p_value <- kruskal_result$p.value
# Calculate the number of groups
k <- length(unique(Ref_both$group))
# Calculate the total number of observations
N <- nrow(Ref_both)
Z <- sqrt(H)

#indicates the proportion of total variability attributable to the factor. Values range from 0 to 1, with higher values indicating a larger effect.
eta_squared <- (H - (k - 1)) / (N - 1)
eta_squared #0.0
#Similar to eta-sq144uared, but adjusted for the number of groups. It also ranges from 0 to 1
#preferably small example sizes 
epsilon_squared <- (H - k + 1) / (N - k)
epsilon_squared #0.0144
# Rank-biserial-Correlation: provides a straightforward way to understand the effect size in terms of the standard normal distribution. An effect size of r around 0.1 is considered small, around 0.3 is medium, and around 0.5 is large.
r <- Z/sqrt(N)
r #0.12
```